quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa
quarkus.quinoa.ui-dir=src/main/webui



quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bak
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rehasteon





